import { config, dom, library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBell,
  faBook,
  faBug,
  faCalendar,
  faChartArea,
  faCheck,
  faCheckCircle as fasCheckCircle,
  faChevronDown,
  faChevronUp,
  faCircle,
  faClipboard,
  faCode,
  faCog,
  faComment,
  faComments,
  faDownload,
  faEdit,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFlag,
  faGamepad,
  faGem as fasGem,
  faGlobe,
  faGraduationCap,
  faHeartbeat,
  faHome,
  faInfo,
  faInfoCircle,
  faKey,
  faLink,
  faList,
  faLock,
  faMagic,
  faMoneyBillAlt,
  faPaperPlane,
  faPencilAlt,
  faPlay,
  faPlayCircle,
  faPlus,
  faPuzzlePiece,
  faQuestionCircle,
  faReply,
  faSave,
  faSearch,
  faServer,
  faSignOutAlt,
  faSpinner,
  faStar as fasStar,
  faStopCircle,
  faTags,
  faTerminal,
  faThumbsUp as fasThumbsUp,
  faTimes,
  faTimesCircle,
  faTrash,
  faUnlockAlt,
  faUpload,
  faUser,
  faUsers,
  faUserTag,
  faUserTie,
  faWindowClose,
  faWrench
} from "@fortawesome/free-solid-svg-icons";

import {
  faCheckCircle as farCheckCircle,
  faClock,
  faFile,
  faFileArchive,
  faGem as farGem,
  faMinusSquare,
  faPlusSquare,
  faSadTear,
  faStar as farStar,
  faThumbsUp as farThumbsUp
} from "@fortawesome/free-regular-svg-icons";

config.autoAddCss = false;

library.add(
  fasStar,
  fasGem,
  faEye,
  faDownload,
  faServer,
  faComment,
  faWrench,
  faMoneyBillAlt,
  faPuzzlePiece,
  faGamepad,
  faLock,
  faMagic,
  faGlobe,
  faAsterisk,
  faChevronUp,
  faChevronDown,
  faHome,
  faComments,
  faCode,
  faBook,
  faGraduationCap,
  faPlus,
  faUsers,
  faUserTie,
  faUser,
  faBell,
  faFlag,
  fasThumbsUp,
  faChartArea,
  faHeartbeat,
  faList,
  faSignOutAlt,
  farThumbsUp,
  faTrash,
  faPlay,
  faInfoCircle,
  faQuestionCircle,
  faExclamationCircle,
  faSpinner,
  faCircle,
  faArrowRight,
  faCheck,
  faReply,
  faSave,
  faTimes,
  faPencilAlt,
  faArrowLeft,
  faCog,
  faPlayCircle,
  faEdit,
  faKey,
  faCalendar,
  faFile,
  faUpload,
  faPaperPlane,
  faPlusSquare,
  faSearch,
  farStar,
  faExternalLinkAlt,
  faMinusSquare,
  faBug,
  faFileArchive,
  faTerminal,
  faStopCircle,
  faClipboard,
  faWindowClose,
  faSadTear,
  faUnlockAlt,
  farGem,
  faLink,
  farCheckCircle,
  faClock,
  faInfo,
  fasCheckCircle,
  faTimesCircle,
  faEyeSlash,
  faUserTag,
  faTags,
  faExclamationTriangle
);

dom.watch();
