#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
pnpm prettier --write src/types/generated/**.*
git add src/types/generated/**.*
#pnpm run lint:typecheck TODO uncomment when all tsc errors are fixed
DEBUG=eslint:cli-engine pnpm lint-staged
