allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: false
  esbuild: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
  vue-demi: true
