base_path: .
base_url: "https://hangar.crowdin.com"
project_id: 1
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /frontend/app/i18n/locales/en.json
    translation: /frontend/app/i18n/locales/%two_letters_code%.json
    skip_untranslated_strings: true
