base_path: .
base_url: "https://hangar.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /frontend/locales/en.ts
    translation: /frontend/locales/%two_letters_code%.ts
