// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./../components/Announcement.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
  }
}

export { }
