// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./../components/Announcement.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    IconMdiAccountGroup: typeof import('~icons/mdi/account-group')['default']
    IconMdiBookOpen: typeof import('~icons/mdi/book-open')['default']
    IconMdiCodeBraces: typeof import('~icons/mdi/code-braces')['default']
    IconMdiDownloadCircle: typeof import('~icons/mdi/download-circle')['default']
    IconMdiForum: typeof import('~icons/mdi/forum')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    IconMdiKey: typeof import('~icons/mdi/key')['default']
    IconMdiLanguageJava: typeof import('~icons/mdi/language-java')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiPuzzle: typeof import('~icons/mdi/puzzle')['default']
    IconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
  }
}

export { }
