[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="markdownService" type="me.minidigger.hangar.service.MarkdownService" --]
[#-- @ftlvariable name="utils" type="me.minidigger.hangar.util.TemplateHelper" --]
[#-- @ftlvariable name="@helper" type="freemarker.template.TemplateHashModel" --]
[#-- @ftlvariable name="alerts" type="java.util.Map" --]
[#-- @ftlvariable name="routes" type="me.minidigger.hangar.util.RouteHelper" --]
[#-- @ftlvariable name="rand" type="java.util.Random" --]
[#-- @ftlvariable name="headerData" type="me.minidigger.hangar.model.viewhelpers.HeaderData" --]
[#-- @ftlvariable name="rc" type="org.springframework.web.servlet.support.RequestContext" --]
[#-- @ftlvariable name="config" type="me.minidigger.hangar.config.hangar.HangarConfig" --]
