@import models.querymodels.ViewTag

@(tag: ViewTag, tagCount: Int = 0)
@if(tag.data.isEmpty || tagCount > 2 || tag.data.exists(_.length > 14)) {
    <div class="tags">
        <span style="color: @tag.color.foreground; background-color:@tag.color.background; border-color: @tag.color.background" class="tag">@tag.name</span>
    </div>
} else {
    <div class="tags has-addons">
        <span style="color: @tag.color.foreground; background-color:@tag.color.background; border-color: @tag.color.background" class="tag">@tag.name</span>
        <span class="tag">@tag.data.get.take(14)</span>
    </div>
}
