name: Build Frontend

on:
  # allow manual dispatch
  workflow_dispatch:
  # run on PRs
  pull_request:
    paths:
      - 'frontend/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache Pnpm
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install frontend deps
        run: (cd frontend && pnpm install --frozen-lockfile)

      - name: Lint frontend
        env:
          DEBUG: "hangar:*"
        run: (cd frontend && pnpm lint:oxlint && pnpm lint:eslint)

      - name: Build frontend
        env:
          DEBUG: "hangar:*"
        run: (cd frontend && pnpm build)
