name: Build Frontend

on:
  # allow manual dispatch
  workflow_dispatch:
  # run on PRs
  pull_request:
    paths:
      - 'frontend/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: "~/.cache/yarn"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install frontend deps
        env:
          CI: true
        run: (cd frontend && yarn install --frozen-lockfile --cache-folder ~/.cache/yarn)

      - name: Lint frontend
        env:
          CI: true
        run: (cd frontend && yarn lint)

      - name: Build frontend
        env:
          CI: true
          # keep these in sync with compose!
          proxyHost: "http://hangar_new_backend:8080"
          authHost: "https://hangar-auth.benndorf.dev"
          host: "0.0.0.0"
          PUBLIC_HOST: "https://hangar.benndorf.dev"
        run: (cd frontend && yarn build)
